### ISSUE TITLE
Error processing RSS Feed

### ISSUE THREAD

**Issue by cmodijk** [desarrolla2/RSSClient#14]
I'm trying to reed an RSS Feed but I get the exception 'Guid not found'. The GUID inside the RSS looks like this: 

``` xml
<guid isPermaLink="false"/>
```

I can't find if the guid syntax without value is valid or not. The w3c validator says "guid should not be blank" but my RSS reader Vienna can open the feed.

**Comment by desarrolla2** [comment]
please include the full feed, so we can include it in the test suite, and fix the bug.

https://github.com/desarrolla2/RSSClient/tree/master/tests/Desarrolla2/RSSClient/Parser/Test/data/rss20

Regards!

**Comment by cmodijk** [comment]
The full feed can be found here: https://banen.bol.com/feed/?post_type=vacature

**Comment by desarrolla2** [comment]
Ok, im reading the RFC and saids `<guid> is an optional sub-element of <item>.`
