### ISSUE TITLE
No element 'desc' in RSS 2.0 spec

### ISSUE THREAD

**Issue by itn3rd77** [desarrolla2/RSSClient#2]
Reading your description the client is only tested and known to work with RSS 2.0. But according to the RSS 2.0 spec  (http://www.rssboard.org/rss-specification#hrelementsOfLtitemgt) there is no element of <item> named <desc> as in the parseDOMNode function of the RSSClient class. The correct element name is <description> and I couldn´t find any RSS feed I use with an <desc> element.

Is this known to work with any RSS 2.0 feed or am I wrong?

Regards,

Ingo

**Comment by desarrolla2** [comment]
You are right, it was a bug

**Comment by itn3rd77** [comment]
Ok fine. Thanks for fixing!
