### ISSUE TITLE
Make sorting optional

### ISSUE THREAD

**Issue by bkosborne** [desarrolla2/RSSClient#22]
I see that `NodeCollection` has a `short` method (should this be "sort"?) that sorts all the nodes in the collection by pubDate. 
1. Why is this done? Shouldn't you leave it up to the feed provider to sort the items as they want?
2. Thoughts on making this optional? Could easily just be an attribute on `RSSClient` and conditionally not call `$nodes->short();` in the `fetch` method

I noticed you started a new project. Perhaps you can add the functionality there insteaD?

**Comment by desarrolla2** [comment]
hi @bkosborne i'm working in a new version of this project called FastFeed[1], in this new project you will sort the results as you want (or not sort).

I'm working in my first release, probably will release it tomorrow, i'm only need to write documentation and other final touches.

You are right method should be sort!!!. ( short was a typo )

[1] https://github.com/FastFeed/FastFeed

**Comment by bkosborne** [comment]
good to know, thanks. I'll follow the new repo and will look to use it in a project. Thanks for the great work.

**Comment by desarrolla2** [comment]
@bkosborne i just write the english version of documentation[1], if you have time i appreciate that you revise it, I'm not fluent in English!!

Comments are wellcome

Regards!

[1] https://github.com/FastFeed/FastFeed/blob/master/doc/en/index.md

**Comment by bkosborne** [comment]
Sure, I'll fork and provide a PR

**Comment by desarrolla2** [comment]
thanks!
