### ISSUE TITLE
How to access other elements ?

### ISSUE THREAD

**Issue by rohitkhatri** [desarrolla2/RSSClient#24]
I am trying to fetch [this](http://blog.digitalinsights.in/feed) RSS feed, but it has big description in content section, how can i access the content element of item.

Please help me.
Thanks.

**Comment by desarrolla2** [comment]
currently i dont support RSSClient anymore, please update to https://github.com/FastFeed/FastFeed.

If you want to continue ussing RSSClient, you have to modify this file https://github.com/desarrolla2/RSSClient/blob/master/src/Desarrolla2/RSSClient/Factory/RSS20NodeFactory.php, adding a custom setDescription method

**Comment by rohitkhatri** [comment]
Thanks for your support, but I switched to FastFeed and added custom function :-)
