### ISSUE TITLE
RssCache class not found

### ISSUE THREAD

**Issue by dominte-ca** [desarrolla2/RSSClient#7]
Symfony 2.1.9

Fatal error: Class 'Desarrolla2\RSSClient\Client\RSSCache' not found in {app_dir}\app\cache\dev\appDevDebugProjectContainer.php on line 1996

composer.json:

"desarrolla2/cache": "dev-master",
"ezyang/htmlpurifier": "dev-master",
"desarrolla2/rss-client-bundle": "dev-master"

controller:

$this->client = $this->get('rss_client');
$feeds = $this->client->fetch('tumblr_blog');
var_dump($feeds); die;

config.yml

rss_client:
   cache:
      adapter: Desarrolla2\Cache\Adapter\NotCache # This is the default
      ttl:     3600 # This is the default
   channels:  
      tumblr_blog:
         - 'http://www.osukaru.es/feed/'

**Comment by desarrolla2** [comment]
Hi.

Can you run "composer update" and try again?

If not work, please copy and paste composer.lock

Regards!

**Comment by desarrolla2** [comment]
This is a issue related to RSSClientBundle, i will fix it soon
